/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PeriodRouteImport } from './routes/period'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as HoldingsIndexRouteImport } from './routes/holdings.index'
import { Route as HoldingsOrgIdRouteImport } from './routes/holdings.$orgId'
import { Route as HousesHouseIdRouteImport } from './routes/houses.$houseId'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSheetsTokenRouteImport } from './routes/api/sheets.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodRoute = PeriodRouteImport.update({
  id: '/period',
  path: '/period',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsIndexRoute = HoldingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HoldingsRoute,
} as any)
const HoldingsOrgIdRoute = HoldingsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => HoldingsRoute,
} as any)
const HousesHouseIdRoute = HousesHouseIdRouteImport.update({
  id: '/houses/$houseId',
  path: '/houses/$houseId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSheetsTokenRoute = ApiSheetsTokenRouteImport.update({
  id: '/api/sheets/$token',
  path: '/api/sheets/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cost': typeof CostRoute
  '/demo': typeof DemoRoute
  '/feed': typeof FeedRoute
  '/forecasts': typeof ForecastsRoute
  '/guide': typeof GuideRoute
  '/holdings': typeof HoldingsRouteWithChildren
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/period': typeof PeriodRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/tools': typeof ToolsRoute
  '/holdings/$orgId': typeof HoldingsOrgIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/holdings/': typeof HoldingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sheets/$token': typeof ApiSheetsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cost': typeof CostRoute
  '/demo': typeof DemoRoute
  '/feed': typeof FeedRoute
  '/forecasts': typeof ForecastsRoute
  '/guide': typeof GuideRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/period': typeof PeriodRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/tools': typeof ToolsRoute
  '/holdings/$orgId': typeof HoldingsOrgIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/holdings': typeof HoldingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sheets/$token': typeof ApiSheetsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cost': typeof CostRoute
  '/demo': typeof DemoRoute
  '/feed': typeof FeedRoute
  '/forecasts': typeof ForecastsRoute
  '/guide': typeof GuideRoute
  '/holdings': typeof HoldingsRouteWithChildren
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/period': typeof PeriodRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/tools': typeof ToolsRoute
  '/holdings/$orgId': typeof HoldingsOrgIdRoute
  '/houses/$houseId': typeof HousesHouseIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/holdings/': typeof HoldingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sheets/$token': typeof ApiSheetsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cost'
    | '/demo'
    | '/feed'
    | '/forecasts'
    | '/guide'
    | '/holdings'
    | '/journal'
    | '/login'
    | '/period'
    | '/report'
    | '/settings'
    | '/team'
    | '/tools'
    | '/holdings/$orgId'
    | '/houses/$houseId'
    | '/sites/$siteId'
    | '/holdings/'
    | '/api/auth/$'
    | '/api/sheets/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cost'
    | '/demo'
    | '/feed'
    | '/forecasts'
    | '/guide'
    | '/journal'
    | '/login'
    | '/period'
    | '/report'
    | '/settings'
    | '/team'
    | '/tools'
    | '/holdings/$orgId'
    | '/houses/$houseId'
    | '/sites/$siteId'
    | '/holdings'
    | '/api/auth/$'
    | '/api/sheets/$token'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cost'
    | '/demo'
    | '/feed'
    | '/forecasts'
    | '/guide'
    | '/holdings'
    | '/journal'
    | '/login'
    | '/period'
    | '/report'
    | '/settings'
    | '/team'
    | '/tools'
    | '/holdings/$orgId'
    | '/houses/$houseId'
    | '/sites/$siteId'
    | '/holdings/'
    | '/api/auth/$'
    | '/api/sheets/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CostRoute: typeof CostRoute
  DemoRoute: typeof DemoRoute
  FeedRoute: typeof FeedRoute
  ForecastsRoute: typeof ForecastsRoute
  GuideRoute: typeof GuideRoute
  HoldingsRoute: typeof HoldingsRouteWithChildren
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  PeriodRoute: typeof PeriodRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  ToolsRoute: typeof ToolsRoute
  HousesHouseIdRoute: typeof HousesHouseIdRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSheetsTokenRoute: typeof ApiSheetsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/period': {
      id: '/period'
      path: '/period'
      fullPath: '/period'
      preLoaderRoute: typeof PeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings/': {
      id: '/holdings/'
      path: '/'
      fullPath: '/holdings/'
      preLoaderRoute: typeof HoldingsIndexRouteImport
      parentRoute: typeof HoldingsRoute
    }
    '/holdings/$orgId': {
      id: '/holdings/$orgId'
      path: '/$orgId'
      fullPath: '/holdings/$orgId'
      preLoaderRoute: typeof HoldingsOrgIdRouteImport
      parentRoute: typeof HoldingsRoute
    }
    '/houses/$houseId': {
      id: '/houses/$houseId'
      path: '/houses/$houseId'
      fullPath: '/houses/$houseId'
      preLoaderRoute: typeof HousesHouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sheets/$token': {
      id: '/api/sheets/$token'
      path: '/api/sheets/$token'
      fullPath: '/api/sheets/$token'
      preLoaderRoute: typeof ApiSheetsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HoldingsRouteChildren {
  HoldingsOrgIdRoute: typeof HoldingsOrgIdRoute
  HoldingsIndexRoute: typeof HoldingsIndexRoute
}

const HoldingsRouteChildren: HoldingsRouteChildren = {
  HoldingsOrgIdRoute: HoldingsOrgIdRoute,
  HoldingsIndexRoute: HoldingsIndexRoute,
}

const HoldingsRouteWithChildren = HoldingsRoute._addFileChildren(
  HoldingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CostRoute: CostRoute,
  DemoRoute: DemoRoute,
  FeedRoute: FeedRoute,
  ForecastsRoute: ForecastsRoute,
  GuideRoute: GuideRoute,
  HoldingsRoute: HoldingsRouteWithChildren,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  PeriodRoute: PeriodRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  ToolsRoute: ToolsRoute,
  HousesHouseIdRoute: HousesHouseIdRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSheetsTokenRoute: ApiSheetsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
